<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.special import roots_hermitenorm
roots, weights = roots_hermitenorm(5)
roots

array([-2.85697001, -1.35562618,  0.        ,  1.35562618,  2.85697001])

In [ ]:
weights

array([0.02821815, 0.55666179, 1.33686841, 0.55666179, 0.02821815])

Verify that the values in `roots` are roots of the Hermite polynomial
$He_5(x)$.


In [ ]:
from scipy.special import eval_hermitenorm
eval_hermitenorm(5, roots)

array([ 1.59872116e-14, -5.32907052e-15,  0.00000000e+00,  5.32907052e-15,
       -1.59872116e-14])

The values of $He_5(x)$ evaluated at the roots are indeed either zero
or rather close to it. The increasing values for larger roots can be explained
by the increasing derivative of the Hermite polynomial at the roots.

Verify that the sum of the weights equals the integral from $-\infty$
to $\infty$ of $\exp(-x^2/2)$ which evaluates to $\sqrt{2\pi}$.
There are two ways to obtain the sum of weights, both yielding the expected
result.


In [ ]:
sum(weights)

np.float64(2.5066282746310002)

In [ ]:
roots, weights, sum_of_weights = roots_hermitenorm(5, mu=True)
sum_of_weights

np.float64(2.5066282746310002)

In [ ]:
from math import exp, pi, sqrt
sqrt(2*pi)

2.5066282746310002

Roots and weights obtained from the Hermite polynomial $He_n(x)$
are used in Gauss-Hermite quadrature where the integral from $-\infty$
to $\infty$ of $f(x)\exp(-x^2/2)$ is evaluated. Roots and weights
for order $n$ are expected to yield the exact result for polynomials
$f(x)$ of a maximal order of $2n-1$.


In [ ]:
f = lambda x: x**4
weights @ f(roots)

np.float64(7.519884823892987)

This result is indeed very close to the exact value of $3\sqrt{2\pi}$.


In [ ]:
3*sqrt(2*pi)

7.519884823893001

In general, Gauss-Hermite quadrature will only yield an approximate value of
the integral. Consider the integral from $-\infty$ to $\infty$ of
$\cos(x)\exp(-x^2/2)$ which evaluates to $\sqrt{2\pi}\exp(-1/2)$.


In [ ]:
import numpy as np
weights @ np.cos(roots)

np.float64(1.520412469197972)

In [ ]:
sqrt(2*pi) * exp(-0.5)

1.5203469010662807

In order to improve the accuracy obtained from Gauss-Hermite quadrature, a
large number of nodes can be chosen.


In [ ]:
roots, weights = roots_hermitenorm(50)
weights @ np.cos(roots)

np.float64(1.5203469010662798)