<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.linalg import svdvals
m = np.array([[1.0, 0.0],
              [2.0, 3.0],
              [1.0, 1.0],
              [0.0, 2.0],
              [1.0, 0.0]])
svdvals(m)

array([ 4.28091555,  1.63516424])

If the input matrix has more than two dimensions, it is interpreted as a batch of
two-dimensional matrices:


In [ ]:
mm = np.stack((m, 2*m))
svdvals(mm)

array([[4.28091555, 1.63516424],
       [8.56183109, 3.27032847]])

We can verify the maximum singular value of `m` by computing the maximum
length of `m @ u` over all the unit vectors `u` in the (x,y) plane.
We approximate "all" the unit vectors with a large sample. Because
of linearity, we only need the unit vectors with angles in ``[0, pi]``.


In [ ]:
t = np.linspace(0, np.pi, 2000)
u = np.array([np.cos(t), np.sin(t)])
np.linalg.norm(m @ u, axis=0).max()

4.2809152422538475

`p` is a projection matrix with rank 1. With exact arithmetic,
its singular values would be ``[1, 0, 0, 0]``.


In [ ]:
v = np.array([0.1, 0.3, 0.9, 0.3])
p = np.outer(v, v)
svdvals(p)

array([  1.00000000e+00,   2.02021698e-17,   1.56692500e-17,
         8.15115104e-34])

The singular values of an orthogonal matrix are all 1. Here, we
create a random orthogonal matrix by using the ``rvs()`` method of
`scipy.stats.ortho_group`.


In [ ]:
from scipy.stats import ortho_group
orth = ortho_group.rvs(4)
svdvals(orth)

array([ 1.,  1.,  1.,  1.])