<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import RigidTransform as Tf
from scipy.spatial.transform import Rotation as R
import numpy as np

Creating from a single rotation and translation:


In [ ]:
t = np.array([2, 3, 4])
r = R.from_euler("ZYX", [90, 30, 0], degrees=True)
r.as_matrix()

array([[ 0.       , -1.,  0.        ],
       [ 0.8660254,  0.,  0.5       ],
       [-0.5      ,  0.,  0.8660254 ]])

In [ ]:
tf = Tf.from_components(t, r)
tf.rotation.as_matrix()

array([[ 0.       , -1.,  0.        ],
       [ 0.8660254,  0.,  0.5       ],
       [-0.5      ,  0.,  0.8660254 ]])

In [ ]:
tf.translation

array([2., 3., 4.])

In [ ]:
tf.single

True

When applying a transform to a vector ``v``, the result is the same as
if the transform was applied to the vector in the following way:
``tf.apply(v) == translation + rotation.apply(v)``


In [ ]:
r.apply([1, 0, 0])

array([0.       , 0.8660254, -0.5     ])

In [ ]:
t + r.apply([1, 0, 0])

array([2.       , 3.8660254,  3.5     ])

In [ ]:
tf.apply([1, 0, 0])

array([2.       , 3.8660254,  3.5     ])