<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import RigidTransform as Tf
from scipy.spatial.transform import Rotation as R
import numpy as np

Creating a single identity transform:


In [ ]:
tf = Tf.identity()
tf.as_matrix()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
tf.single

True

The identity transform can be applied to a vector without effect:


In [ ]:
tf.apply([1, 2, 3])

array([1., 2., 3.])

The identity transform when composed with another transform has no
effect:


In [ ]:
rng = np.random.default_rng()
t = rng.random(3)
r = R.random(rng=rng)
tf = Tf.from_components(t, r)
np.allclose((Tf.identity() * tf).as_matrix(),
            tf.as_matrix(), atol=1e-12)

True

Multiple identity transforms can be generated at once:


In [ ]:
tf = Tf.identity(2)
tf.as_matrix()

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],
       [[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]])

In [ ]:
tf.single

False

In [ ]:
len(tf)

2