<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Simple operations:


In [ ]:
import numpy as np
from scipy.signal import upfirdn
upfirdn([1, 1, 1], [1, 1, 1])   # FIR filter

array([ 1.,  2.,  3.,  2.,  1.])

In [ ]:
upfirdn([1], [1, 2, 3], 3)  # upsampling with zeros insertion

array([ 1.,  0.,  0.,  2.,  0.,  0.,  3.])

In [ ]:
upfirdn([1, 1, 1], [1, 2, 3], 3)  # upsampling with sample-and-hold

array([ 1.,  1.,  1.,  2.,  2.,  2.,  3.,  3.,  3.])

In [ ]:
upfirdn([.5, 1, .5], [1, 1, 1], 2)  # linear interpolation

array([ 0.5,  1. ,  1. ,  1. ,  1. ,  1. ,  0.5])

In [ ]:
upfirdn([1], np.arange(10), 1, 3)  # decimation by 3

array([ 0.,  3.,  6.,  9.])

In [ ]:
upfirdn([.5, 1, .5], np.arange(10), 2, 3)  # linear interp, rate 2/3

array([ 0. ,  1. ,  2.5,  4. ,  5.5,  7. ,  8.5])

Apply a single filter to multiple signals:


In [ ]:
x = np.reshape(np.arange(8), (4, 2))
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

Apply along the last dimension of ``x``:


In [ ]:
h = [1, 1]
upfirdn(h, x, 2)

array([[ 0.,  0.,  1.,  1.],
       [ 2.,  2.,  3.,  3.],
       [ 4.,  4.,  5.,  5.],
       [ 6.,  6.,  7.,  7.]])

Apply along the 0th dimension of ``x``:


In [ ]:
upfirdn(h, x, 2, axis=0)

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 2.,  3.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 6.,  7.]])