<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.spatial.distance import pdist

``x`` is an array of five points in three-dimensional space.


In [ ]:
x = np.array([[2, 0, 2], [2, 2, 3], [-2, 4, 5], [0, 1, 9], [2, 2, 4]])

``pdist(x)`` with no additional arguments computes the 10 pairwise
Euclidean distances:


In [ ]:
pdist(x)

array([2.23606798, 6.40312424, 7.34846923, 2.82842712, 4.89897949,
       6.40312424, 1.        , 5.38516481, 4.58257569, 5.47722558])

The following computes the pairwise Minkowski distances with ``p = 3.5``:


In [ ]:
pdist(x, metric='minkowski', p=3.5)

array([2.04898923, 5.1154929 , 7.02700737, 2.43802731, 4.19042714,
       6.03956994, 1.        , 4.45128103, 4.10636143, 5.0619695 ])

The pairwise city block or Manhattan distances:


In [ ]:
pdist(x, metric='cityblock')

array([ 3., 11., 10.,  4.,  8.,  9.,  1.,  9.,  7.,  8.])