<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import Rotation as R
import numpy as np

A rotation can be represented as a quaternion with either scalar-last
(default) or scalar-first component order.
This is shown for a single rotation:


In [ ]:
r = R.from_matrix(np.eye(3))
r.as_quat()

array([0., 0., 0., 1.])

In [ ]:
r.as_quat(scalar_first=True)

array([1., 0., 0., 0.])

The resulting shape of the quaternion is always the shape of the Rotation
object with an added last dimension of size 4. E.g. when the `Rotation` object
contains an N-dimensional array (N, M, K) of rotations, the result will be a
4-dimensional array:


In [ ]:
r = R.from_rotvec(np.ones((2, 3, 4, 3)))
r.as_quat().shape

(2, 3, 4, 4)

Quaternions can be mapped from a redundant double cover of the
rotation space to a canonical representation with a positive w term.


In [ ]:
r = R.from_quat([0, 0, 0, -1])
r.as_quat()

array([0. , 0. , 0. , -1.])

In [ ]:
r.as_quat(canonical=True)

array([0. , 0. , 0. , 1.])