<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

We'll use data from [2], Table 1. The null hypothesis is that the means of
the distributions underlying the samples and control are equal.

First, we test that the means of the distributions underlying the samples
and control are unequal (``alternative='two-sided'``, the default).


In [ ]:
import numpy as np
from scipy.stats import dunnett
samples = [[3.8, 2.7, 4.0, 2.4], [2.8, 3.4, 3.7, 2.2, 2.0]]
control = [2.9, 3.0, 2.5, 2.6, 3.2]
res = dunnett(*samples, control=control)
res.statistic

array([ 0.90874545, -0.05007117])

In [ ]:
res.pvalue

array([0.58325114, 0.99819341])

Now, we test that the means of the distributions underlying the samples are
greater than the mean of the distribution underlying the control.


In [ ]:
res = dunnett(*samples, control=control, alternative='greater')
res.statistic

array([ 0.90874545, -0.05007117])

In [ ]:
res.pvalue

array([0.30230596, 0.69115597])

For a more detailed example, see :ref:`hypothesis_dunnett`.