<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Three-quarters of the given values lie below a given score:


In [ ]:
import numpy as np
from scipy import stats
stats.percentileofscore([1, 2, 3, 4], 3)

75.0

With multiple matches, note how the scores of the two matches, 0.6
and 0.8 respectively, are averaged:


In [ ]:
stats.percentileofscore([1, 2, 3, 3, 4], 3)

70.0

Only 2/5 values are strictly less than 3:


In [ ]:
stats.percentileofscore([1, 2, 3, 3, 4], 3, kind='strict')

40.0

But 4/5 values are less than or equal to 3:


In [ ]:
stats.percentileofscore([1, 2, 3, 3, 4], 3, kind='weak')

80.0

The average between the weak and the strict scores is:


In [ ]:
stats.percentileofscore([1, 2, 3, 3, 4], 3, kind='mean')

60.0

Score arrays (of any dimensionality) are supported:


In [ ]:
stats.percentileofscore([1, 2, 3, 3, 4], [2, 3])

array([40., 70.])

The inputs can be infinite:


In [ ]:
stats.percentileofscore([-np.inf, 0, 1, np.inf], [1, 2, np.inf])

array([75., 75., 100.])

If `a` is empty, then the resulting percentiles are all `nan`:


In [ ]:
stats.percentileofscore([], [1, 2])

array([nan, nan])