<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.sparse.linalg import LaplacianNd
from scipy.sparse import diags, csgraph
from scipy.linalg import eigvalsh

The one-dimensional Laplacian demonstrated below for pure Neumann boundary
conditions on a regular grid with ``n=6`` grid points is exactly the
negative graph Laplacian for the undirected linear graph with ``n``
vertices using the sparse adjacency matrix ``G`` represented by the
famous tri-diagonal matrix:


In [ ]:
n = 6
G = diags(np.ones(n - 1), 1, format='csr')
Lf = csgraph.laplacian(G, symmetrized=True, form='function')
grid_shape = (n, )
lap = LaplacianNd(grid_shape, boundary_conditions='neumann')
np.array_equal(lap.matmat(np.eye(n)), -Lf(np.eye(n)))

True

Since all matrix entries of the Laplacian are integers, ``'int8'`` is
the default dtype for storing matrix representations.


In [ ]:
lap.tosparse()

<DIAgonal sparse array of dtype 'int8'
    with 16 stored elements (3 diagonals) and shape (6, 6)>

In [ ]:
lap.toarray()

array([[-1,  1,  0,  0,  0,  0],
       [ 1, -2,  1,  0,  0,  0],
       [ 0,  1, -2,  1,  0,  0],
       [ 0,  0,  1, -2,  1,  0],
       [ 0,  0,  0,  1, -2,  1],
       [ 0,  0,  0,  0,  1, -1]], dtype=int8)

In [ ]:
np.array_equal(lap.matmat(np.eye(n)), lap.toarray())

True

In [ ]:
np.array_equal(lap.tosparse().toarray(), lap.toarray())

True

Any number of extreme eigenvalues and/or eigenvectors can be computed.


In [ ]:
lap = LaplacianNd(grid_shape, boundary_conditions='periodic')
lap.eigenvalues()

array([-4., -3., -3., -1., -1.,  0.])

In [ ]:
lap.eigenvalues()[-2:]

array([-1.,  0.])

In [ ]:
lap.eigenvalues(2)

array([-1.,  0.])

In [ ]:
lap.eigenvectors(1)

array([[0.40824829],
       [0.40824829],
       [0.40824829],
       [0.40824829],
       [0.40824829],
       [0.40824829]])

In [ ]:
lap.eigenvectors(2)

array([[ 0.5       ,  0.40824829],
       [ 0.        ,  0.40824829],
       [-0.5       ,  0.40824829],
       [-0.5       ,  0.40824829],
       [ 0.        ,  0.40824829],
       [ 0.5       ,  0.40824829]])

In [ ]:
lap.eigenvectors()

array([[ 0.40824829,  0.28867513,  0.28867513,  0.5       ,  0.5       ,
         0.40824829],
       [-0.40824829, -0.57735027, -0.57735027,  0.        ,  0.        ,
         0.40824829],
       [ 0.40824829,  0.28867513,  0.28867513, -0.5       , -0.5       ,
         0.40824829],
       [-0.40824829,  0.28867513,  0.28867513, -0.5       , -0.5       ,
         0.40824829],
       [ 0.40824829, -0.57735027, -0.57735027,  0.        ,  0.        ,
         0.40824829],
       [-0.40824829,  0.28867513,  0.28867513,  0.5       ,  0.5       ,
         0.40824829]])

The two-dimensional Laplacian is illustrated on a regular grid with
``grid_shape = (2, 3)`` points in each dimension.


In [ ]:
grid_shape = (2, 3)
n = np.prod(grid_shape)

Numeration of grid points is as follows:


In [ ]:
np.arange(n).reshape(grid_shape + (-1,))

array([[[0],
        [1],
        [2]],
<BLANKLINE>
       [[3],
        [4],
        [5]]])

Each of the boundary conditions ``'dirichlet'``, ``'periodic'``, and
``'neumann'`` is illustrated separately; with ``'dirichlet'``


In [ ]:
lap = LaplacianNd(grid_shape, boundary_conditions='dirichlet')
lap.tosparse()

<Compressed Sparse Row sparse array of dtype 'int8'
    with 20 stored elements and shape (6, 6)>

In [ ]:
lap.toarray()

array([[-4,  1,  0,  1,  0,  0],
       [ 1, -4,  1,  0,  1,  0],
       [ 0,  1, -4,  0,  0,  1],
       [ 1,  0,  0, -4,  1,  0],
       [ 0,  1,  0,  1, -4,  1],
       [ 0,  0,  1,  0,  1, -4]], dtype=int8)

In [ ]:
np.array_equal(lap.matmat(np.eye(n)), lap.toarray())

True

In [ ]:
np.array_equal(lap.tosparse().toarray(), lap.toarray())

True

In [ ]:
lap.eigenvalues()

array([-6.41421356, -5.        , -4.41421356, -3.58578644, -3.        ,
       -1.58578644])

In [ ]:
eigvals = eigvalsh(lap.toarray().astype(np.float64))
np.allclose(lap.eigenvalues(), eigvals)

True

In [ ]:
np.allclose(lap.toarray() @ lap.eigenvectors(),
            lap.eigenvectors() @ np.diag(lap.eigenvalues()))

True

with ``'periodic'``


In [ ]:
lap = LaplacianNd(grid_shape, boundary_conditions='periodic')
lap.tosparse()

<Compressed Sparse Row sparse array of dtype 'int8'
    with 24 stored elements and shape (6, 6)>

In [ ]:
lap.toarray()

    array([[-4,  1,  1,  2,  0,  0],
           [ 1, -4,  1,  0,  2,  0],
           [ 1,  1, -4,  0,  0,  2],
           [ 2,  0,  0, -4,  1,  1],
           [ 0,  2,  0,  1, -4,  1],
           [ 0,  0,  2,  1,  1, -4]], dtype=int8)

In [ ]:
np.array_equal(lap.matmat(np.eye(n)), lap.toarray())

True

In [ ]:
np.array_equal(lap.tosparse().toarray(), lap.toarray())

True

In [ ]:
lap.eigenvalues()

array([-7., -7., -4., -3., -3.,  0.])

In [ ]:
eigvals = eigvalsh(lap.toarray().astype(np.float64))
np.allclose(lap.eigenvalues(), eigvals)

True

In [ ]:
np.allclose(lap.toarray() @ lap.eigenvectors(),
            lap.eigenvectors() @ np.diag(lap.eigenvalues()))

True

and with ``'neumann'``


In [ ]:
lap = LaplacianNd(grid_shape, boundary_conditions='neumann')
lap.tosparse()

<Compressed Sparse Row sparse array of dtype 'int8'
    with 20 stored elements and shape (6, 6)>

In [ ]:
lap.toarray()

array([[-2,  1,  0,  1,  0,  0],
       [ 1, -3,  1,  0,  1,  0],
       [ 0,  1, -2,  0,  0,  1],
       [ 1,  0,  0, -2,  1,  0],
       [ 0,  1,  0,  1, -3,  1],
       [ 0,  0,  1,  0,  1, -2]], dtype=int8)

In [ ]:
np.array_equal(lap.matmat(np.eye(n)), lap.toarray())

True

In [ ]:
np.array_equal(lap.tosparse().toarray(), lap.toarray())

True

In [ ]:
lap.eigenvalues()

array([-5., -3., -3., -2., -1.,  0.])

In [ ]:
eigvals = eigvalsh(lap.toarray().astype(np.float64))
np.allclose(lap.eigenvalues(), eigvals)

True

In [ ]:
np.allclose(lap.toarray() @ lap.eigenvectors(),
            lap.eigenvectors() @ np.diag(lap.eigenvalues()))

True