<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.special import roots_chebys
roots, weights = roots_chebys(5)
roots

array([-1.73205081e+00, -1.00000000e+00,  1.22464680e-16,  1.00000000e+00,
        1.73205081e+00])

In [ ]:
weights

array([0.26179939, 0.78539816, 1.04719755, 0.78539816, 0.26179939])

Verify that the values in `roots` are roots of the Chebyshev polynomial of
first kind $S_5(x)$.


In [ ]:
from scipy.special import eval_chebys
eval_chebys(5, roots)

array([-1.33226763e-15, -1.77635684e-15,  3.67394040e-16, -8.88178420e-16,
        1.33226763e-15])

The values of $S_5(x)$ evaluated at the roots are indeed very close to zero.

Verify that the sum of the weights equals the integral from -2 to 2 of
$\sqrt{1-(x/2)^2}$ which evaluates to $\pi$. There are two ways
to obtain the sum of weights, both resulting in $\pi$ within numerical
precision.


In [ ]:
sum(weights)

np.float64(3.141592653589793)

In [ ]:
roots, weights, sum_of_weights = roots_chebys(5, mu=True)
sum_of_weights

3.141592653589793

Roots and weights obtained from the Chebyshev polynomial of the second kind
$S_n(x)$ are used in Gauss-Chebyshev quadrature where the integral from
-2 to 2 of $f(x)\sqrt{1-(x/2)^2}$ is evaluated. Roots and weights for
order $n$ are expected to yield the exact result for polynomials $f(x)$
of a maximal order of $2n-1$.


In [ ]:
f = lambda x: x**4
weights @ f(roots)

np.float64(6.283185307179585)

The exact result is $2\pi$.


In [ ]:
from math import pi
2*pi

6.283185307179586

In general, Gauss-Chebyshev quadrature will only yield an approximate value of the
integral. Consider the integral from -2 to 2 of $\cos(x)\sqrt{1-(x/2)^2}$.


In [ ]:
import numpy as np
weights @ np.cos(roots)

np.float64(1.8118352216010754)

Check against the result of `scipy.integrate.quad`.


In [ ]:
from scipy.integrate import quad
result, abserror = quad(lambda x: np.cos(x) * np.sqrt(1-(x/2)**2), -2, 2)
result

1.8118344191919165

The latter result has an estimated absolute error of


In [ ]:
abserror

1.5300099409643053e-08