<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.fft import fft, hfft
import numpy as np
a = 2 * np.pi * np.arange(10) / 10
signal = np.cos(a) + 3j * np.sin(3 * a)
fft(signal).round(10)

array([ -0.+0.j,   5.+0.j,  -0.+0.j,  15.-0.j,   0.+0.j,   0.+0.j,
        -0.+0.j, -15.-0.j,   0.+0.j,   5.+0.j])

In [ ]:
hfft(signal[:6]).round(10) # Input first half of signal

array([  0.,   5.,   0.,  15.,  -0.,   0.,   0., -15.,  -0.,   5.])

In [ ]:
hfft(signal, 10)  # Input entire signal and truncate

array([  0.,   5.,   0.,  15.,  -0.,   0.,   0., -15.,  -0.,   5.])