<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

The following example computes the partial-fraction
expansion of b(z) / a(z):


In [ ]:
import numpy as np
from scipy import signal
b = np.array([1, 0.3])
a = np.array([1, -0.75, 0.125])
r, p, k = signal.residuez(b, a)
r

array([-2.2,  3.2])

In [ ]:
p

array([0.25, 0.5 ])

There is no direct term here, so `k` is empty:


In [ ]:
k

array([], dtype=float64)

Get `b` and `a` back with `invresz`:


In [ ]:
signal.invresz(r, p, k)

(array([1. , 0.3]), array([ 1.   , -0.75 ,  0.125]))

An example where `k` is not empty:


In [ ]:
b = np.array([2, -1, 0.1])
a = np.array([1, -0.5])
r, p, k = signal.residuez(b, a)
r, p

(array([0.4]), array([0.5]))

In [ ]:
k

array([ 1.6, -0.2])