<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.linalg import convolution_matrix
A = convolution_matrix([-1, 4, -2], 5, mode='same')
A

array([[ 4, -1,  0,  0,  0],
       [-2,  4, -1,  0,  0],
       [ 0, -2,  4, -1,  0],
       [ 0,  0, -2,  4, -1],
       [ 0,  0,  0, -2,  4]])

Compare multiplication by `A` with the use of `numpy.convolve`.


In [ ]:
x = np.array([1, 2, 0, -3, 0.5])
A @ x

array([  2. ,   6. ,  -1. , -12.5,   8. ])

Verify that ``A @ x`` produced the same result as applying the
convolution function.


In [ ]:
np.convolve([-1, 4, -2], x, mode='same')

array([  2. ,   6. ,  -1. , -12.5,   8. ])

For comparison to the case ``mode='same'`` shown above, here are the
matrices produced by ``mode='full'`` and ``mode='valid'`` for the
same coefficients and size.


In [ ]:
convolution_matrix([-1, 4, -2], 5, mode='full')

array([[-1,  0,  0,  0,  0],
       [ 4, -1,  0,  0,  0],
       [-2,  4, -1,  0,  0],
       [ 0, -2,  4, -1,  0],
       [ 0,  0, -2,  4, -1],
       [ 0,  0,  0, -2,  4],
       [ 0,  0,  0,  0, -2]])

In [ ]:
convolution_matrix([-1, 4, -2], 5, mode='valid')

array([[-2,  4, -1,  0,  0],
       [ 0, -2,  4, -1,  0],
       [ 0,  0, -2,  4, -1]])