<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.linalg import lstsq
import matplotlib.pyplot as plt

Suppose we have the following data:


In [ ]:
x = np.array([1, 2.5, 3.5, 4, 5, 7, 8.5])
y = np.array([0.3, 1.1, 1.5, 2.0, 3.2, 6.6, 8.6])

We want to fit a quadratic polynomial of the form ``y = a + b*x**2``
to this data.  We first form the "design matrix" M, with a constant
column of 1s and a column containing ``x**2``:


In [ ]:
M = x[:, np.newaxis]**[0, 2]
M

array([[  1.  ,   1.  ],
       [  1.  ,   6.25],
       [  1.  ,  12.25],
       [  1.  ,  16.  ],
       [  1.  ,  25.  ],
       [  1.  ,  49.  ],
       [  1.  ,  72.25]])

We want to find the least-squares solution to ``M.dot(p) = y``,
where ``p`` is a vector with length 2 that holds the parameters
``a`` and ``b``.


In [ ]:
p, res, rnk, s = lstsq(M, y)
p

array([ 0.20925829,  0.12013861])

Plot the data and the fitted curve.


In [ ]:
plt.plot(x, y, 'o', label='data')
xx = np.linspace(0, 9, 101)
yy = p[0] + p[1]*xx**2
plt.plot(xx, yy, label='least squares fit, $y = a + bx^2$')
plt.xlabel('x')
plt.ylabel('y')
plt.legend(framealpha=1, shadow=True)
plt.grid(alpha=0.25)
plt.show()

As an illustration of the "batching" feature (see :ref:`linalg_batch` for details),
suppose that we want to compare least-squares fits of the given data with two
models: a quadratic model above, and one with an additional linear term,
``y = a + b*x**2 + c*x``.
To this end, we construct the design matrix for ``y = a + b*x**2 + c*x``, and
extend ``M`` to have three columns:


In [ ]:
M1 = np.hstack((M, np.zeros((7, 1))))
M2 = x[:, np.newaxis] ** [0, 2, 1]
MM = np.stack((M1, M2))
x, res, rnk, s = lstsq(MM, y)
x

array([[0.20925829, 0.12013861, 0.        ],
       [0.0578403 , 0.11262261, 0.07701453]])

In [ ]:
rnk

array([2, 3])

Note that the rows of the ``x`` solution are equivalent to using ``M1`` and ``M2``,
respectively.
In a similar vein, to simulate an effect of random noise on ``y``, you can turn
it into an array with multiple columns, where each column corresponds to a specific
realization of the noise.
