<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Univariate samples, approximate p-value.


In [ ]:
import numpy as np
from scipy import stats
x = [1, 2, 3, 4, 5]
y = [5, 6, 7, 8, 7]
res = stats.spearmanrho(x, y)
res.statistic

np.float64(0.8207826816681233)

In [ ]:
res.pvalue

np.float64(0.08858700531354405)

Univariate samples, exact p-value.


In [ ]:
res = stats.spearmanrho(x, y, method=stats.PermutationMethod())
res.statistic

np.float64(0.8207826816681233)

In [ ]:
res.pvalue

np.float64(0.13333333333333333)

Batch of univariate samples, one vectorized call.


In [ ]:
rng = np.random.default_rng()
x2 = rng.standard_normal((2, 100))
y2 = rng.standard_normal((2, 100))
res = stats.spearmanrho(x2, y2, axis=-1)
res.statistic

array([ 0.16585659, -0.12151215])

In [ ]:
res.pvalue

array([0.0991155 , 0.22846869])

Bivariate samples using standard broadcasting rules.


In [ ]:
res = stats.spearmanrho(x2[np.newaxis, :], x2[:, np.newaxis], axis=-1)
res.statistic

array([[ 1.        , -0.14670267],
       [-0.14670267,  1.        ]])

In [ ]:
res.pvalue

array([[0.        , 0.14526128],
       [0.14526128, 0.        ]])