<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Compute the first 4 real roots and the derivatives at the roots of
$Y_1$:


In [ ]:
import numpy as np
from scipy.special import y1_zeros
zeros, grads = y1_zeros(4)
with np.printoptions(precision=5):
    print(f"Roots: {zeros}")
    print(f"Gradients: {grads}")

Roots: [ 2.19714+0.j  5.42968+0.j  8.59601+0.j 11.74915+0.j]
Gradients: [ 0.52079+0.j -0.34032+0.j  0.27146+0.j -0.23246+0.j]

Extract the real parts:


In [ ]:
realzeros = zeros.real
realzeros

array([ 2.19714133,  5.42968104,  8.59600587, 11.74915483])

Plot $Y_1$ and the first four computed roots.


In [ ]:
import matplotlib.pyplot as plt
from scipy.special import y1
xmin = 0
xmax = 13
x = np.linspace(xmin, xmax, 500)
zeros, grads = y1_zeros(4)
fig, ax = plt.subplots()
ax.hlines(0, xmin, xmax, color='k')
ax.plot(x, y1(x), label=r'$Y_1$')
ax.scatter(zeros.real, np.zeros((4, )), s=30, c='r',
           label=r'$Y_1$_zeros', zorder=5)
ax.set_ylim(-0.5, 0.5)
ax.set_xlim(xmin, xmax)
plt.legend()
plt.show()

Compute the first 4 complex roots and the derivatives at the roots of
$Y_1$ by setting ``complex=True``:


In [ ]:
y1_zeros(4, True)

(array([ -0.50274327+0.78624371j,  -3.83353519+0.56235654j,
         -7.01590368+0.55339305j, -10.17357383+0.55127339j]),
 array([-0.45952768+1.31710194j,  0.04830191-0.69251288j,
        -0.02012695+0.51864253j,  0.011614  -0.43203296j]))