<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Given `a` and `b`, solve for `x`:


In [ ]:
import numpy as np
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])
from scipy.linalg import solve
x = solve(a, b)
x

array([ 2., -2.,  9.])

In [ ]:
a @ x == b

array([ True,  True,  True], dtype=bool)

Batches of matrices are supported, with and without structure detection:
(See :ref:`linalg_batch` for further details of handling batched inputs.)


In [ ]:
a = np.arange(12).reshape(3, 2, 2)   # a batch of 3 2x2 matrices
A = a.transpose(0, 2, 1) @ a    # A is a batch of 3 positive definite matrices
b = np.ones(2)
solve(A, b)      # this automatically detects that A is pos.def.

array([[ 1. , -0.5],
       [ 3. , -2.5],
       [ 5. , -4.5]])

In [ ]:
solve(A, b, assume_a='pos')   # bypass structucture detection

array([[ 1. , -0.5],
       [ 3. , -2.5],
       [ 5. , -4.5]])

Note that the structure detection runs per-slice: in the example above, each of the
two slices will be independently discovered as being positive definite. Setting an
explicit ``assume_a`` argument bypasses structure detection and uses the provided
value without checking:


In [ ]:
a = np.stack((np.eye(2), np.arange(1, 5).reshape(2, 2)))
b = [1, 1]
solve(a, b, assume_a="diagonal")

array([[1.  , 1.  ],
       [1.  , 0.25]])   # the second row is incorrect