<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

You can insert knots into a B-spline.


In [ ]:
from scipy.interpolate import splrep, insert
import numpy as np
x = np.linspace(0, 10, 5)
y = np.sin(x)
tck = splrep(x, y)
tck[0]

array([ 0.,  0.,  0.,  0.,  5., 10., 10., 10., 10.])

A knot is inserted:


In [ ]:
tck_inserted = insert(3, tck)
tck_inserted[0]

array([ 0.,  0.,  0.,  0.,  3.,  5., 10., 10., 10., 10.])

Some knots are inserted:


In [ ]:
tck_inserted2 = insert(8, tck, m=3)
tck_inserted2[0]

array([ 0.,  0.,  0.,  0.,  5.,  8.,  8.,  8., 10., 10., 10., 10.])