<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.special import roots_laguerre
roots, weights = roots_laguerre(5)
roots

array([ 0.26356032,  1.41340306,  3.59642577,  7.08581001, 12.64080084])

In [ ]:
weights

array([5.21755611e-01, 3.98666811e-01, 7.59424497e-02, 3.61175868e-03,
       2.33699724e-05])

Verify that the values in `roots` are roots of the Laguerre polynomial
$L_5(x)$.


In [ ]:
from scipy.special import eval_laguerre
eval_laguerre(5, roots)

array([-5.55111512e-17, -5.55111512e-17,  2.22044605e-16, -1.77635684e-15,
       -5.68434189e-14])

The values of $L_5(x)$ evaluated at the roots are indeed rather close
to zero. The increasing values for larger roots can be explained by the
increasing derivative of the Laguerre polynomial at the roots.

Verify that the sum of the weights equals the integral from 0 to $\infty$
of $\exp(-x)$ which evaluates to 1. There are two ways to obtain the
sum of weights, both resulting in 1 within numerical precision.


In [ ]:
sum(weights)

np.float64(0.9999999999999998)

In [ ]:
roots, weights, sum_of_weights = roots_laguerre(5, mu=True)
sum_of_weights

np.float64(1.0)

Roots and weights obtained from the Laguerre polynomial $L_n(x)$
are used in Gauss-Laguerre quadrature where the integral from 0 to
$\infty$ of $f(x)\exp(-x)$ is evaluated. Roots and weights
for order $n$ are expected to yield the exact result for polynomials
$f(x)$ of a maximal order of $2n-1$.


In [ ]:
f = lambda x: x**4
weights @ f(roots)

np.float64(24.000000000000014)

This result is indeed very close to the exact value of 24.

In general, Gauss-Laguerre quadrature will only yield an approximate value of the
integral. Consider the integral from 0 to $\infty$ of $\cos(x)\exp(-x)$
which evaluates to 1/2.


In [ ]:
import numpy as np
weights @ np.cos(roots)

np.float64(0.5005384852176379)