<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

The LU decomposition can be used to solve matrix equations. Consider:


In [ ]:
import numpy as np
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import splu
A = csc_matrix([[1,2,0,4], [1,0,0,1], [1,0,2,1], [2,2,1,0.]])

This can be solved for a given right-hand side:


In [ ]:
lu = splu(A)
b = np.array([1, 2, 3, 4])
x = lu.solve(b)
A.dot(x)

array([ 1.,  2.,  3.,  4.])

The ``lu`` object also contains an explicit representation of the
decomposition. The permutations are represented as mappings of
indices:


In [ ]:
lu.perm_r

array([2, 1, 3, 0], dtype=int32)  # may vary

In [ ]:
lu.perm_c

array([0, 1, 3, 2], dtype=int32)  # may vary

The L and U factors are sparse matrices in CSC format:


In [ ]:
lu.L.toarray()

array([[ 1. ,  0. ,  0. ,  0. ],  # may vary
       [ 0.5,  1. ,  0. ,  0. ],
       [ 0.5, -1. ,  1. ,  0. ],
       [ 0.5,  1. ,  0. ,  1. ]])

In [ ]:
lu.U.toarray()

array([[ 2. ,  2. ,  0. ,  1. ],  # may vary
       [ 0. , -1. ,  1. , -0.5],
       [ 0. ,  0. ,  5. , -1. ],
       [ 0. ,  0. ,  0. ,  2. ]])

The permutation matrices can be constructed:


In [ ]:
Pr = csc_matrix((np.ones(4), (lu.perm_r, np.arange(4))))
Pc = csc_matrix((np.ones(4), (np.arange(4), lu.perm_c)))

We can reassemble the original matrix:


In [ ]:
(Pr.T @ (lu.L @ lu.U) @ Pc.T).toarray()

array([[ 1.,  2.,  0.,  4.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  0.,  2.,  1.],
       [ 2.,  2.,  1.,  0.]])