<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

You can insert knots into a B-spline:


In [ ]:
import numpy as np
from scipy.interpolate import BSpline, make_interp_spline
x = np.linspace(0, 10, 5)
y = np.sin(x)
spl = make_interp_spline(x, y, k=3)
spl.t

array([ 0.,  0.,  0.,  0.,  5., 10., 10., 10., 10.])

Insert a single knot


In [ ]:
spl_1 = spl.insert_knot(3)
spl_1.t

array([ 0.,  0.,  0.,  0.,  3.,  5., 10., 10., 10., 10.])

Insert a multiple knot


In [ ]:
spl_2 = spl.insert_knot(8, m=3)
spl_2.t

array([ 0.,  0.,  0.,  0.,  5.,  8.,  8.,  8., 10., 10., 10., 10.])