<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import Rotation as R
import numpy as np

Composition of two single rotations:


In [ ]:
p = R.from_quat([0, 0, 1, 1])
q = R.from_quat([1, 0, 0, 1])
p.as_matrix()

array([[ 0., -1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.]])

In [ ]:
q.as_matrix()

array([[ 1.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  1.,  0.]])

In [ ]:
r = p * q
r.as_matrix()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

Composition of two objects containing equal number of rotations:


In [ ]:
p = R.from_quat([[0, 0, 1, 1], [1, 0, 0, 1]])
q = R.from_rotvec([[np.pi/4, 0, 0], [-np.pi/4, 0, np.pi/4]])
p.as_quat()

array([[0.        , 0.        , 0.70710678, 0.70710678],
       [0.70710678, 0.        , 0.        , 0.70710678]])

In [ ]:
q.as_quat()

array([[ 0.38268343,  0.        ,  0.        ,  0.92387953],
       [-0.37282173,  0.        ,  0.37282173,  0.84971049]])

In [ ]:
r = p * q
r.as_quat()

array([[ 0.27059805,  0.27059805,  0.65328148,  0.65328148],
       [ 0.33721128, -0.26362477,  0.26362477,  0.86446082]])