<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import RigidTransform as Tf
from scipy.spatial.transform import Rotation as R
import numpy as np

Compose two transforms:


In [ ]:
tf1 = Tf.from_translation([1, 0, 0])
tf2 = Tf.from_translation([0, 1, 0])
tf = tf1 * tf2
tf.translation

array([1., 1., 0.])

In [ ]:
tf.single

True

When applied to a vector, the composition of two transforms is applied
in right-to-left order.


In [ ]:
t1, r1 = [1, 2, 3], R.from_euler('z', 60, degrees=True)
t2, r2 = [0, 1, 0], R.from_euler('x', 30, degrees=True)
tf1 = Tf.from_components(t1, r1)
tf2 = Tf.from_components(t2, r2)
tf = tf1 * tf2
tf.apply([1, 0, 0])

array([0.6339746, 3.3660254, 3.       ])

In [ ]:
tf1.apply(tf2.apply([1, 0, 0]))

array([0.6339746, 3.3660254, 3.       ])

When at least one of the transforms is not single, the result is a stack
of transforms.


In [ ]:
tf1 = Tf.from_translation([1, 0, 0])
tf2 = Tf.from_translation([[0, 2, 0], [0, 0, 3]])
tf = tf1 * tf2
tf.translation

array([[1., 2., 0.],
       [1., 0., 3.]])

In [ ]:
tf.single

False

In [ ]:
len(tf)

2

Broadcasting rules apply when composing multiple transforms at a time.


In [ ]:
tf1 = Tf.from_translation(np.ones((5, 1, 3)))  # Shape (5, 1, 3)
tf2 = Tf.from_translation(np.ones((1, 4, 3)))  # Shape (1, 4, 3)
tf = tf1 * tf2  # Shape (5, 4, 3)
tf.translation.shape

(5, 4, 3)