<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import RigidTransform as Tf
import numpy as np

A power of 2 returns the transform composed with itself:


In [ ]:
tf = Tf.from_translation([1, 2, 3])
(tf ** 2).translation

array([2., 4., 6.])

In [ ]:
(tf ** 2).as_matrix()

array([[1., 0., 0., 2.],
       [0., 1., 0., 4.],
       [0., 0., 1., 6.],
       [0., 0., 0., 1.]])

A negative power returns the inverse of the transform raised to the
absolute value of `n`:


In [ ]:
(tf ** -2).translation

array([-2., -4., -6.])

In [ ]:
np.allclose((tf ** -2).as_matrix(), (tf.inv() ** 2).as_matrix(),
            atol=1e-12)

True

A power of 0 returns the identity transform:


In [ ]:
(tf ** 0).as_matrix()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

A power of 1 returns a copy of the original transform:


In [ ]:
(tf ** 1).as_matrix()

array([[1., 0., 0., 1.],
       [0., 1., 0., 2.],
       [0., 0., 1., 3.],
       [0., 0., 0., 1.]])

A fractional power returns a transform with a scaled rotation and
translated along the screw axis. Here we take the square root of the
transform, which when squared recovers the original transform:


In [ ]:
tf_half = (tf ** 0.5)
tf_half.translation

array([0.5, 1., 1.5])

In [ ]:
(tf_half ** 2).as_matrix()

array([[1., 0., 0., 1.],
       [0., 1., 0., 2.],
       [0., 0., 1., 3.],
       [0., 0., 0., 1.]])