<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Evaluate a simple example function on the points of a regular 3-D grid:


In [ ]:
import numpy as np
from scipy.interpolate import interpn
def value_func_3d(x, y, z):
    return 2 * x + 3 * y - z
x = np.linspace(0, 4, 5)
y = np.linspace(0, 5, 6)
z = np.linspace(0, 6, 7)
points = (x, y, z)
values = value_func_3d(*np.meshgrid(*points, indexing='ij'))

Evaluate the interpolating function at a point


In [ ]:
point = np.array([2.21, 3.12, 1.15])
print(interpn(points, values, point))

[12.63]

Compare with value at point by function


In [ ]:
value_func_3d(*point)

12.63 # up to rounding

Since the function is linear, the interpolation is exact using linear method.

If ``fill_value=None``, then values outside of the domain are extrapolated.


In [ ]:
x = np.linspace(0, 10, 11)
y = np.linspace(0, 15, 16)
def value_func_2d(x, y):
   return 5 * x - 3 * y
points = (x, y)
values = value_func_2d(*np.meshgrid(*points, indexing='ij'))
xi = np.array([[25, 36]])
interpn(points, values, xi, method='linear', bounds_error=False,
        fill_value=None)

array([17.])

If a ``fill_value`` is specified, any points outside the domain will be set to
``fill_value``.


In [ ]:
interpn(points, values, xi, method='linear', bounds_error=False, fill_value=42)

array([42.])

When one axis is a single grid point, interpolation is only done at that
coordinate. Any other value along that axis is out of bounds, and set
to ``fill_value`` (if there is one).

Evaluate interpolation function at a point outside of the single-point axis


In [ ]:
x = np.array([0.0]) # x axis has length 1
y = np.linspace(0, 10, 11)
points = (x, y)
values = value_func_2d(*np.meshgrid(*points, indexing='ij'))
xi = np.array([[1.0, 0.5]])
interpn(points, values, xi, method='linear', bounds_error=False,
        fill_value = 42)

array([42.])

Evaluate interpolation function at a point on the single-point axis


In [ ]:
xi = np.array([[0.0, 0.5]])
interpn(points, values, xi, method='linear', bounds_error=False,
        fill_value = 42)

array([-1.5])   # interpolation as normal along y