<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.linalg import solve_circulant, solve, circulant, lstsq

In [ ]:
c = np.array([2, 2, 4])
b = np.array([1, 2, 3])
solve_circulant(c, b)

array([ 0.75, -0.25,  0.25])

Compare that result to solving the system with `scipy.linalg.solve`:


In [ ]:
solve(circulant(c), b)

array([ 0.75, -0.25,  0.25])

A singular example:


In [ ]:
c = np.array([1, 1, 0, 0])
b = np.array([1, 2, 3, 4])

Calling ``solve_circulant(c, b)`` will raise a `LinAlgError`.  For the
least square solution, use the option ``singular='lstsq'``:


In [ ]:
solve_circulant(c, b, singular='lstsq')

array([ 0.25,  1.25,  2.25,  1.25])

Compare to `scipy.linalg.lstsq`:


In [ ]:
x, resid, rnk, s = lstsq(circulant(c), b)
x

array([ 0.25,  1.25,  2.25,  1.25])

A broadcasting example:

Suppose we have the vectors of two circulant matrices stored in an array
with shape (2, 5), and three `b` vectors stored in an array with shape
(3, 5).  For example,


In [ ]:
c = np.array([[1.5, 2, 3, 0, 0], [1, 1, 4, 3, 2]])
b = np.arange(15).reshape(-1, 5)

We want to solve all combinations of circulant matrices and `b` vectors,
with the result stored in an array with shape (2, 3, 5). When we
disregard the axes of `c` and `b` that hold the vectors of coefficients,
the shapes of the collections are (2,) and (3,), respectively, which are
not compatible for broadcasting. To have a broadcast result with shape
(2, 3), we add a trivial dimension to `c`: ``c[:, np.newaxis, :]`` has
shape (2, 1, 5). The last dimension holds the coefficients of the
circulant matrices, so when we call `solve_circulant`, we can use the
default ``caxis=-1``. The coefficients of the `b` vectors are in the last
dimension of the array `b`, so we use ``baxis=-1``. If we use the
default `outaxis`, the result will have shape (5, 2, 3), so we'll use
``outaxis=-1`` to put the solution vectors in the last dimension.


In [ ]:
x = solve_circulant(c[:, np.newaxis, :], b, baxis=-1, outaxis=-1)
x.shape

(2, 3, 5)

In [ ]:
np.set_printoptions(precision=3)  # For compact output of numbers.
x

array([[[-0.118,  0.22 ,  1.277, -0.142,  0.302],
        [ 0.651,  0.989,  2.046,  0.627,  1.072],
        [ 1.42 ,  1.758,  2.816,  1.396,  1.841]],
       [[ 0.401,  0.304,  0.694, -0.867,  0.377],
        [ 0.856,  0.758,  1.149, -0.412,  0.831],
        [ 1.31 ,  1.213,  1.603,  0.042,  1.286]]])

Check by solving one pair of `c` and `b` vectors (cf. ``x[1, 1, :]``):


In [ ]:
solve_circulant(c[1], b[1, :])

array([ 0.856,  0.758,  1.149, -0.412,  0.831])