<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.stats import matrix_t
M = np.arange(6).reshape(3,2)
M

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
Sigma = np.diag([1,2,3])
Sigma

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
Omega = 0.3*np.identity(2)
Omega

array([[ 0.3,  0. ],
       [ 0. ,  0.3]])

In [ ]:
X = M + 0.1
X

array([[ 0.1,  1.1],
       [ 2.1,  3.1],
       [ 4.1,  5.1]])

In [ ]:
df = 3
matrix_t.pdf(X, mean=M, row_spread=Sigma, col_spread=Omega, df=df)

0.9972880280135796

Alternatively, the object may be called (as a function) to fix the mean
and spread parameters, returning a "frozen" matrix t
random variable:


In [ ]:
rv = matrix_t(mean=None, row_spread=1, col_spread=1, df=1)
# Frozen object with the same methods but holding the given
# mean and spreads and degrees of freedom fixed.