<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.special import log_expit, expit

In [ ]:
log_expit([-3.0, 0.25, 2.5, 5.0])

array([-3.04858735, -0.57593942, -0.07888973, -0.00671535])

Large negative values:


In [ ]:
log_expit([-100, -500, -1000])

array([ -100.,  -500., -1000.])

Note that ``expit(-1000)`` returns 0, so the naive implementation
``log(expit(-1000))`` return ``-inf``.

Large positive values:


In [ ]:
log_expit([29, 120, 400])

array([-2.54366565e-013, -7.66764807e-053, -1.91516960e-174])

Compare that to the naive implementation:


In [ ]:
np.log(expit([29, 120, 400]))

array([-2.54463117e-13,  0.00000000e+00,  0.00000000e+00])

The first value is accurate to only 3 digits, and the larger inputs
lose all precision and return 0.