<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Design a 6th order low-pass elliptic digital filter for a system with a
sampling rate of 8000 Hz that has a pass-band corner frequency of
1000 Hz. The ripple in the pass-band should not exceed 0.087 dB, and
the attenuation in the stop-band should be at least 90 dB.

In the following call to `ellip`, we could use ``output='sos'``,
but for this example, we'll use ``output='zpk'``, and then convert
to SOS format with `zpk2sos`:


In [ ]:
from scipy import signal
import numpy as np
z, p, k = signal.ellip(6, 0.087, 90, 1000/(0.5*8000), output='zpk')

Now convert to SOS format.


In [ ]:
sos = signal.zpk2sos(z, p, k)

The coefficients of the numerators of the sections:


In [ ]:
sos[:, :3]

array([[0.0014152 , 0.00248677, 0.0014152 ],
       [1.        , 0.72976874, 1.        ],
       [1.        , 0.17607852, 1.        ]])

The symmetry in the coefficients occurs because all the zeros are on the
unit circle.

The coefficients of the denominators of the sections:


In [ ]:
sos[:, 3:]

array([[ 1.        , -1.32544025,  0.46989976],
       [ 1.        , -1.26118294,  0.62625924],
       [ 1.        , -1.2570723 ,  0.8619958 ]])

The next example shows the effect of the `pairing` option.  We have a
system with three poles and three zeros, so the SOS array will have
shape (2, 6). The means there is, in effect, an extra pole and an extra
zero at the origin in the SOS representation.


In [ ]:
z1 = np.array([-1, -0.5-0.5j, -0.5+0.5j])
p1 = np.array([0.75, 0.8+0.1j, 0.8-0.1j])

With ``pairing='nearest'`` (the default), we obtain


In [ ]:
signal.zpk2sos(z1, p1, 1)

array([[ 1.  ,  1.  ,  0.5 ,  1.  , -0.75,  0.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  , -1.6 ,  0.65]])

The first section has the zeros {-0.5-0.05j, -0.5+0.5j} and the poles
{0, 0.75}, and the second section has the zeros {-1, 0} and poles
{0.8+0.1j, 0.8-0.1j}. Note that the extra pole and zero at the origin
have been assigned to different sections.

With ``pairing='keep_odd'``, we obtain:


In [ ]:
signal.zpk2sos(z1, p1, 1, pairing='keep_odd')

array([[ 1.  ,  1.  ,  0.  ,  1.  , -0.75,  0.  ],
       [ 1.  ,  1.  ,  0.5 ,  1.  , -1.6 ,  0.65]])

The extra pole and zero at the origin are in the same section.
The first section is, in effect, a first-order section.

With ``pairing='minimal'``, the first-order section doesn't have
the extra pole and zero at the origin:


In [ ]:
signal.zpk2sos(z1, p1, 1, pairing='minimal')

array([[ 0.  ,  1.  ,  1.  ,  0.  ,  1.  , -0.75],
       [ 1.  ,  1.  ,  0.5 ,  1.  , -1.6 ,  0.65]])