<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy import stats
res = stats.spearmanr([1, 2, 3, 4, 5], [5, 6, 7, 8, 7])
res.statistic

0.8207826816681233

In [ ]:
res.pvalue

0.08858700531354381

In [ ]:
rng = np.random.default_rng()
x2n = rng.standard_normal((100, 2))
y2n = rng.standard_normal((100, 2))
res = stats.spearmanr(x2n)
res.statistic, res.pvalue

(-0.07960396039603959, 0.4311168705769747)

In [ ]:
res = stats.spearmanr(x2n[:, 0], x2n[:, 1])
res.statistic, res.pvalue

(-0.07960396039603959, 0.4311168705769747)

In [ ]:
res = stats.spearmanr(x2n, y2n)
res.statistic

array([[ 1. , -0.07960396, -0.08314431, 0.09662166],
       [-0.07960396, 1. , -0.14448245, 0.16738074],
       [-0.08314431, -0.14448245, 1. , 0.03234323],
       [ 0.09662166, 0.16738074, 0.03234323, 1. ]])

In [ ]:
res.pvalue

array([[0. , 0.43111687, 0.41084066, 0.33891628],
       [0.43111687, 0. , 0.15151618, 0.09600687],
       [0.41084066, 0.15151618, 0. , 0.74938561],
       [0.33891628, 0.09600687, 0.74938561, 0. ]])

In [ ]:
res = stats.spearmanr(x2n.T, y2n.T, axis=1)
res.statistic

array([[ 1. , -0.07960396, -0.08314431, 0.09662166],
       [-0.07960396, 1. , -0.14448245, 0.16738074],
       [-0.08314431, -0.14448245, 1. , 0.03234323],
       [ 0.09662166, 0.16738074, 0.03234323, 1. ]])

In [ ]:
res = stats.spearmanr(x2n, y2n, axis=None)
res.statistic, res.pvalue

(0.044981624540613524, 0.5270803651336189)

In [ ]:
res = stats.spearmanr(x2n.ravel(), y2n.ravel())
res.statistic, res.pvalue

(0.044981624540613524, 0.5270803651336189)

In [ ]:
rng = np.random.default_rng()
xint = rng.integers(10, size=(100, 2))
res = stats.spearmanr(xint)
res.statistic, res.pvalue

(0.09800224850707953, 0.3320271757932076)

For small samples, consider performing a permutation test instead of
relying on the asymptotic p-value. Note that to calculate the null
distribution of the statistic (for all possibly pairings between
observations in sample ``x`` and ``y``), only one of the two inputs needs
to be permuted.


In [ ]:
x = [1.76405235, 0.40015721, 0.97873798,
2.2408932, 1.86755799, -0.97727788]
y = [2.71414076, 0.2488, 0.87551913,
2.6514917, 2.01160156, 0.47699563]

In [ ]:
def statistic(x): # permute only `x`
    return stats.spearmanr(x, y).statistic
res_exact = stats.permutation_test((x,), statistic,
    permutation_type='pairings')
res_asymptotic = stats.spearmanr(x, y)
res_exact.pvalue, res_asymptotic.pvalue # asymptotic pvalue is too low

(0.10277777777777777, 0.07239650145772594)

For a more detailed example, see :ref:`hypothesis_spearmanr`.