<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Suppose we wish to minimize the following function.


In [ ]:
def f(x, c=1):
    return (x - c)**2 + 2

First, we must find a valid bracket. The function is unimodal,
so `bracket_minium` will easily find a bracket.


In [ ]:
from scipy.optimize import elementwise
res_bracket = elementwise.bracket_minimum(f, 0)
res_bracket.success

True

In [ ]:
res_bracket.bracket

(0.0, 0.5, 1.5)

Indeed, the bracket points are ordered and the function value
at the middle bracket point is less than at the surrounding
points.


In [ ]:
xl, xm, xr = res_bracket.bracket
fl, fm, fr = res_bracket.f_bracket
(xl < xm < xr) and (fl > fm <= fr)

True

Once we have a valid bracket, `find_minimum` can be used to provide
an estimate of the minimizer.


In [ ]:
res_minimum = elementwise.find_minimum(f, res_bracket.bracket)
res_minimum.x

1.0000000149011612

The function value changes by only a few ULPs within the bracket, so
the minimizer cannot be determined much more precisely by evaluating
the function alone (i.e. we would need its derivative to do better).


In [ ]:
import numpy as np
fl, fm, fr = res_minimum.f_bracket
(fl - fm) / np.spacing(fm), (fr - fm) / np.spacing(fm)

(0.0, 2.0)

Therefore, a precise minimum of the function is given by:


In [ ]:
res_minimum.f_x

2.0

`bracket_minimum` and `find_minimum` accept arrays for most arguments.
For instance, to find the minimizers and minima for a few values of the
parameter ``c`` at once:


In [ ]:
c = np.asarray([1, 1.5, 2])
res_bracket = elementwise.bracket_minimum(f, 0, args=(c,))
res_bracket.bracket

(array([0. , 0.5, 0.5]), array([0.5, 1.5, 1.5]), array([1.5, 2.5, 2.5]))

In [ ]:
res_minimum = elementwise.find_minimum(f, res_bracket.bracket, args=(c,))
res_minimum.x

array([1.00000001, 1.5       , 2.        ])

In [ ]:
res_minimum.f_x

array([2., 2., 2.])