<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import Rotation as R
import numpy as np

Represent a single rotation:


In [ ]:
r = R.from_euler('z', 90, degrees=True)
r.as_rotvec()

array([0.        , 0.        , 1.57079633])

In [ ]:
r.as_rotvec().shape

(3,)

Represent a rotation in degrees:


In [ ]:
r = R.from_euler('YX', (-90, -90), degrees=True)
s = r.as_rotvec(degrees=True)
s

array([-69.2820323, -69.2820323, -69.2820323])

In [ ]:
np.linalg.norm(s)

120.00000000000001

Represent a stack with a single rotation:


In [ ]:
r = R.from_quat([[0, 0, 1, 1]])
r.as_rotvec()

array([[0.        , 0.        , 1.57079633]])

In [ ]:
r.as_rotvec().shape

(1, 3)

Represent multiple rotations in a single object:


In [ ]:
r = R.from_quat([[0, 0, 1, 1], [1, 1, 0, 1]])
r.as_rotvec()

array([[0.        , 0.        , 1.57079633],
       [1.35102172, 1.35102172, 0.        ]])

In [ ]:
r.as_rotvec().shape

(2, 3)