<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import Rotation as R
import numpy as np

Single rotation applied on a single vector:


In [ ]:
vector = np.array([1, 0, 0])
r = R.from_rotvec([0, 0, np.pi/2])
r.as_matrix()

array([[ 2.22044605e-16, -1.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  2.22044605e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
r.apply(vector)

array([2.22044605e-16, 1.00000000e+00, 0.00000000e+00])

In [ ]:
r.apply(vector).shape

(3,)

Single rotation applied on multiple vectors:


In [ ]:
vectors = np.array([
[1, 0, 0],
[1, 2, 3]])
r = R.from_rotvec([0, 0, np.pi/4])
r.as_matrix()

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [ ]:
r.apply(vectors)

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  2.12132034,  3.        ]])

In [ ]:
r.apply(vectors).shape

(2, 3)

Multiple rotations on a single vector:


In [ ]:
r = R.from_rotvec([[0, 0, np.pi/4], [np.pi/2, 0, 0]])
vector = np.array([1,2,3])
r.as_matrix()

array([[[ 7.07106781e-01, -7.07106781e-01,  0.00000000e+00],
        [ 7.07106781e-01,  7.07106781e-01,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],
       [[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  2.22044605e-16, -1.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00,  2.22044605e-16]]])

In [ ]:
r.apply(vector)

array([[-0.70710678,  2.12132034,  3.        ],
       [ 1.        , -3.        ,  2.        ]])

In [ ]:
r.apply(vector).shape

(2, 3)

Multiple rotations on multiple vectors. Each rotation is applied on the
corresponding vector:


In [ ]:
r = R.from_euler('zxy', [
[0, 0, 90],
[45, 30, 60]], degrees=True)
vectors = [
[1, 2, 3],
[1, 0, -1]]
r.apply(vectors)

array([[ 3.        ,  2.        , -1.        ],
       [-0.09026039,  1.11237244, -0.86860844]])

In [ ]:
r.apply(vectors).shape

(2, 3)

It is also possible to apply the inverse rotation:


In [ ]:
r = R.from_euler('zxy', [
[0, 0, 90],
[45, 30, 60]], degrees=True)
vectors = [
[1, 2, 3],
[1, 0, -1]]
r.apply(vectors, inverse=True)

array([[-3.        ,  2.        ,  1.        ],
       [ 1.09533535, -0.8365163 ,  0.3169873 ]])