<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Solve the banded system ``A x = b``, where
```

[ 4  2 -1  0  0  0]       [1]
[ 2  5  2 -1  0  0]       [2]
A = [-1  2  6  2 -1  0]   b = [2]
[ 0 -1  2  7  2 -1]       [3]
[ 0  0 -1  2  8  2]       [3]
[ 0  0  0 -1  2  9]       [3]

```

In [ ]:
import numpy as np
from scipy.linalg import solveh_banded

``ab`` contains the main diagonal and the nonzero diagonals below the
main diagonal. That is, we use the lower form:


In [ ]:
ab = np.array([[ 4,  5,  6,  7, 8, 9],
               [ 2,  2,  2,  2, 2, 0],
               [-1, -1, -1, -1, 0, 0]])
b = np.array([1, 2, 2, 3, 3, 3])
x = solveh_banded(ab, b, lower=True)
x

array([ 0.03431373,  0.45938375,  0.05602241,  0.47759104,  0.17577031,
        0.34733894])

Solve the Hermitian banded system ``H x = b``, where
```

[ 8   2-1j   0     0  ]        [ 1  ]
H = [2+1j  5     1j    0  ]    b = [1+1j]
[ 0   -1j    9   -2-1j]        [1-2j]
[ 0    0   -2+1j   6  ]        [ 0  ]

```
In this example, we put the upper diagonals in the array ``hb``:


In [ ]:
hb = np.array([[0, 2-1j, 1j, -2-1j],
               [8,  5,    9,   6  ]])
b = np.array([1, 1+1j, 1-2j, 0])
x = solveh_banded(hb, b)
x

array([ 0.07318536-0.02939412j,  0.11877624+0.17696461j,
        0.10077984-0.23035393j, -0.00479904-0.09358128j])