<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import RigidTransform as Tf
from scipy.spatial.transform import Rotation as R
import numpy as np

Creating a transform from a single rotation:


In [ ]:
r = R.from_euler("ZYX", [90, 30, 0], degrees=True)
r.apply([1, 0, 0])

array([0.       , 0.8660254, -0.5     ])

In [ ]:
tf = Tf.from_rotation(r)
tf.apply([1, 0, 0])

array([0.       , 0.8660254, -0.5     ])

In [ ]:
tf.single

True

The upper 3x3 submatrix of the transformation matrix is the rotation
matrix:


In [ ]:
np.allclose(tf.as_matrix()[:3, :3], r.as_matrix(), atol=1e-12)

True

Creating multiple transforms from a rotation with N leading dimensions:


In [ ]:
r = R.from_euler("ZYX", [[90, 30, 0], [45, 30, 60]], degrees=True)
r.apply([1, 0, 0])

array([[0.        , 0.8660254 , -0.5       ],
       [0.61237244, 0.61237244, -0.5       ]])

In [ ]:
tf = Tf.from_rotation(r)
tf.apply([1, 0, 0])

array([[0.        , 0.8660254 , -0.5       ],
       [0.61237244, 0.61237244, -0.5       ]])

In [ ]:
tf.single

False

In [ ]:
len(tf)

2