<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Multiply the Toeplitz matrix T with matrix x
```

[ 1 -1 -2 -3]       [1 10]
T = [ 3  1 -1 -2]   x = [2 11]
[ 6  3  1 -1]       [2 11]
[10  6  3  1]       [5 19]

```
To specify the Toeplitz matrix, only the first column and the first
row are needed.


In [ ]:
import numpy as np
c = np.array([1, 3, 6, 10])    # First column of T
r = np.array([1, -1, -2, -3])  # First row of T
x = np.array([[1, 10], [2, 11], [2, 11], [5, 19]])

In [ ]:
from scipy.linalg import toeplitz, matmul_toeplitz
matmul_toeplitz((c, r), x)

array([[-20., -80.],
       [ -7.,  -8.],
       [  9.,  85.],
       [ 33., 218.]])

Check the result by creating the full Toeplitz matrix and
multiplying it by ``x``.


In [ ]:
toeplitz(c, r) @ x

array([[-20, -80],
       [ -7,  -8],
       [  9,  85],
       [ 33, 218]])

The full matrix is never formed explicitly, so this routine
is suitable for very large Toeplitz matrices.


In [ ]:
n = 1000000
matmul_toeplitz([1] + [0]*(n-1), np.ones(n))

array([1., 1., 1., ..., 1., 1., 1.])