<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.sparse import csr_array
from scipy.sparse.linalg import funm_multiply_krylov
from scipy.linalg import expm, solve
A = csr_array([[3, 2, 0], [1, -1, 0], [0, 5, 1]], dtype=float)
b = np.array([2, 4, -1], dtype=float)
t = 0.1

Compute ``y = exp(tA) b``.


In [ ]:
y = funm_multiply_krylov(expm, A, b, t = t)
y

array([3.6164913 , 3.88421511 , 0.96073457])

In [ ]:
ref = expm(t * A.todense()) @ b
err = y - ref
err

array([4.44089210e-16 , 0.00000000e+00 , 2.22044605e-16])

Compute $y = (A^3 - A) b$.


In [ ]:
poly = lambda X : X @ X @ X - X
y = funm_multiply_krylov(poly, A, b)
y

array([132. , 24. , 70.])

In [ ]:
ref = poly(A.todense()) @ b
err = y - ref
err

array([ 0.00000000e+00 , 7.10542736e-15 , -2.84217094e-14])

Compute $y = f(tA) b$, where  $f(X) = X^{-1}(e^{X} - I)$. This is
known as the "phi function" from the exponential integrator literature.


In [ ]:
phim_1 = lambda X : solve(X, expm(X) - np.eye(X.shape[0]))
y = funm_multiply_krylov(phim_1, A, b, t = t)
y

array([ 2.76984306 , 3.92769192 , -0.03111392])

In [ ]:
ref = phim_1(t * A.todense()) @ b
err = y - ref
err

array([ 0.00000000e+00 , 8.88178420e-16 , -4.60742555e-15])