<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
import scipy.special as sc

It has a pole at 0.


In [ ]:
sc.exp1(0)

inf

It has a branch cut on the negative real axis.


In [ ]:
sc.exp1(-1)

nan

In [ ]:
sc.exp1(complex(-1, 0))

(-1.8951178163559368-3.141592653589793j)

In [ ]:
sc.exp1(complex(-1, -0.0))

(-1.8951178163559368+3.141592653589793j)

It approaches 0 along the positive real axis.


In [ ]:
sc.exp1([1, 10, 100, 1000])

array([2.19383934e-01, 4.15696893e-06, 3.68359776e-46, 0.00000000e+00])

It is related to `expi`.


In [ ]:
x = np.array([1, 2, 3, 4])
sc.exp1(x)

array([0.21938393, 0.04890051, 0.01304838, 0.00377935])

In [ ]:
-sc.expi(-x)

array([0.21938393, 0.04890051, 0.01304838, 0.00377935])