<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import RigidTransform as Tf
from scipy.spatial.transform import Rotation as R
import numpy as np

Apply a single transform to a vector. Here the transform is just a
translation, so the result is the vector added to the translation
vector.


In [ ]:
t = np.array([1, 2, 3])
tf = Tf.from_translation(t)
t + np.array([1, 0, 0])

array([2, 2, 3])

In [ ]:
tf.apply([1, 0, 0])

array([2., 2., 3.])

Apply a single transform to a stack of vectors:


In [ ]:
tf.apply([[1, 0, 0], [0, 1, 0]])

array([[2., 2., 3.],
       [1., 3., 3.]])

Apply the inverse of a transform to a vector, so the result is the
negative of the translation vector added to the vector.


In [ ]:
-t + np.array([1, 0, 0])

array([0, -2, -3])

In [ ]:
tf.apply([1, 0, 0], inverse=True)

array([0., -2., -3.])

Broadcasting is supported when applying multiple transforms to an N-dimensional
array of vectors.


In [ ]:
tf = Tf.from_translation(np.ones((4, 5, 1, 3)))
vectors = np.zeros((2, 3))
tf.apply(vectors).shape

(4, 5, 2, 3)

For transforms which are not just pure translations, applying it to a
vector is the same as applying the rotation component to the vector and
then adding the translation component.


In [ ]:
r = R.from_euler('z', 60, degrees=True)
tf = Tf.from_components(t, r)
t + r.apply([1, 0, 0])

array([1.5,       2.8660254, 3.       ])

In [ ]:
tf.apply([1, 0, 0])

array([1.5,       2.8660254, 3.       ])

When applying the inverse of a transform, the result is the negative of
the translation vector added to the vector, and then rotated by the
inverse rotation.


In [ ]:
r.inv().apply(-t + np.array([1, 0, 0]))

array([-1.73205081, -1.        , -3.        ])

In [ ]:
tf.apply([1, 0, 0], inverse=True)

array([-1.73205081, -1.        , -3.        ])