<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.stats import dirichlet

Generate a dirichlet random variable


In [ ]:
quantiles = np.array([0.2, 0.2, 0.6])  # specify quantiles
alpha = np.array([0.4, 5, 15])  # specify concentration parameters
dirichlet.pdf(quantiles, alpha)

0.2843831684937255

The same PDF but following a log scale


In [ ]:
dirichlet.logpdf(quantiles, alpha)

-1.2574327653159187

Once we specify the dirichlet distribution
we can then calculate quantities of interest


In [ ]:
dirichlet.mean(alpha)  # get the mean of the distribution

array([0.01960784, 0.24509804, 0.73529412])

In [ ]:
dirichlet.var(alpha) # get variance

array([0.00089829, 0.00864603, 0.00909517])

In [ ]:
dirichlet.entropy(alpha)  # calculate the differential entropy

-4.3280162474082715

We can also return random samples from the distribution


In [ ]:
dirichlet.rvs(alpha, size=1, random_state=1)

array([[0.00766178, 0.24670518, 0.74563305]])

In [ ]:
dirichlet.rvs(alpha, size=2, random_state=2)

array([[0.01639427, 0.1292273 , 0.85437844],
       [0.00156917, 0.19033695, 0.80809388]])

Alternatively, the object may be called (as a function) to fix
concentration parameters, returning a "frozen" Dirichlet
random variable:


In [ ]:
rv = dirichlet(alpha)
# Frozen object with the same methods but holding the given
# concentration parameters fixed.