<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.linalg import lu_factor
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
lu, piv = lu_factor(A)
piv

array([2, 2, 3, 3], dtype=int32)

Convert LAPACK's ``piv`` array to NumPy index and test the permutation


In [ ]:
def pivot_to_permutation(piv):
    perm = np.arange(len(piv))
    for i in range(len(piv)):
        perm[i], perm[piv[i]] = perm[piv[i]], perm[i]
    return perm

p_inv = pivot_to_permutation(piv)
p_inv

array([2, 0, 3, 1])

In [ ]:
L, U = np.tril(lu, k=-1) + np.eye(4), np.triu(lu)
np.allclose(A[p_inv] - L @ U, np.zeros((4, 4)))

True

The P matrix in P L U is defined by the inverse permutation and
can be recovered using argsort:


In [ ]:
p = np.argsort(p_inv)
p

array([1, 3, 0, 2])

In [ ]:
np.allclose(A - L[p] @ U, np.zeros((4, 4)))

True

or alternatively:


In [ ]:
P = np.eye(4)[p]
np.allclose(A - P @ L @ U, np.zeros((4, 4)))

True