<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.special import roots_chebyu
roots, weights = roots_chebyu(5)
roots

array([-8.66025404e-01, -5.00000000e-01,  6.12323400e-17,  5.00000000e-01,
        8.66025404e-01])

In [ ]:
weights

array([0.13089969, 0.39269908, 0.52359878, 0.39269908, 0.13089969])

Verify that the values in `roots` are roots of the Chebyshev polynomial of
second kind $U_5(x)$.


In [ ]:
from scipy.special import eval_chebyu
eval_chebyu(5, roots)

array([-1.33226763e-15, -1.77635684e-15,  3.67394040e-16, -8.88178420e-16,
        1.33226763e-15])

The values of $U_5(x)$ evaluated at the roots are indeed very close to zero.

Verify that the sum of the weights equals the integral from -1 to 1 of
$\sqrt{1-x^2}$ which evaluates to $\pi/2$. There are two ways
to obtain the sum of weights, both resulting in $\pi/2$ within numerical
precision.


In [ ]:
sum(weights)

np.float64(1.5707963267948966)

In [ ]:
roots, weights, sum_of_weights = roots_chebyu(5, mu=True)
sum_of_weights

1.5707963267948966

Roots and weights obtained from the Chebyshev polynomial of the second kind
$U_n(x)$ are used in Gauss-Chebyshev quadrature where the integral from
-1 to 1 of $f(x)\sqrt{1-x^2}$ is evaluated. Roots and weights for order
$n$ are expected to yield the exact result for polynomials $f(x)$ of
a maximal order of $2n-1$.


In [ ]:
f = lambda x: x**4
weights @ f(roots)

np.float64(0.19634954084936204)

The exact result is $\pi/16$.


In [ ]:
from math import pi
pi/16

0.19634954084936207

In general, Gauss-Chebyshev quadrature will only yield an approximate value of the
integral. Consider the integral from -1 to 1 of $\cos(x)\sqrt{1-x^2}$
which evaluates to $\pi J_1(1)$, where $J_1$ is the Bessel function
of first kind and order 1.


In [ ]:
import numpy as np
weights @ np.cos(roots)

np.float64(1.3824596877989561)

In [ ]:
from scipy.special import jv
pi*jv(1, 1)

np.float64(1.3824596873841686)