<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.special import roots_chebyc
roots, weights = roots_chebyc(5)
roots

array([-1.90211303, -1.1755705 ,  0.        ,  1.1755705 ,  1.90211303])

In [ ]:
weights

array([1.25663706, 1.25663706, 1.25663706, 1.25663706, 1.25663706])

Verify that the values in `roots` are roots of the Chebyshev polynomial of
first kind $C_5(x)$.


In [ ]:
from scipy.special import eval_chebyc
eval_chebyc(5, roots)

array([ 1.77635684e-15,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -1.77635684e-15])

The values of $C_5(x)$ evaluated at the roots are indeed zero or
very close to it.

Verify that the sum of the weights equals the integral from -2 to 2 of
$1/\sqrt{1-(x/2)^2}$ which evaluates to $2\pi$. There are two ways
to obtain the sum of weights, both resulting in $2\pi$ within numerical
precision.


In [ ]:
sum(weights)

np.float64(6.283185307179586)

In [ ]:
roots, weights, sum_of_weights = roots_chebyc(5, mu=True)
sum_of_weights

6.283185307179586

Roots and weights obtained from the Chebyshev polynomial of the first kind
$C_n(x)$ are used in Gauss-Chebyshev quadrature where the integral
from -2 to 2 of $f(x)/\sqrt{1-(x/2)^2}$ is evaluated. Roots and
weights for order $n$ are expected to yield the exact result for polynomials
$f(x)$ of a maximal order of $2n-1$.


In [ ]:
f = lambda x: x**4
weights @ f(roots)

np.float64(37.69911184307752)

The exact result is $12\pi$.


In [ ]:
from math import pi
12*pi

37.69911184307752

In general, Gauss-Chebyshev quadrature will only yield an approximate value of the
integral. Consider the integral from -2 to 2 of $\cos(x)/\sqrt{1-(x/2)^2}$
which evaluates to $2\pi J_0(2)$, where $J_0$ is the Bessel function
of first kind and order 0.


In [ ]:
import numpy as np
weights @ np.cos(roots)

np.float64(1.4067504148408285)

In [ ]:
from scipy.special import jv
2*pi*jv(0, 2)

np.float64(1.4067472539132013)