<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import RigidTransform as Tf
import numpy as np

Creating from a single 6d vector of exponential coordinates:


In [ ]:
tf = Tf.from_exp_coords([
    -2.01041204, -0.52983629, 0.65773501,
    0.10386614, 0.05855009, 0.54959179])
tf.as_matrix()

array([[0.76406621, 0.10504613, -0.63652819, -0.10209961],
       [0.59956454, -0.47987325, 0.64050295, 0.40158789],
       [-0.2381705, -0.87102639, -0.42963687, 0.19637636],
       [0., 0., 0., 1.]])

In [ ]:
tf.single

True

A vector of zeros represents the identity transform:


In [ ]:
tf = Tf.from_exp_coords(np.zeros(6))
tf.as_matrix()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

The last three numbers encode translation. If the first three numbers
are zero, the last three components can be interpreted as the
translation:


In [ ]:
tf_trans = Tf.from_exp_coords([0, 0, 0, 4.3, -2, 3.4])
tf_trans.translation

array([4.3, -2., 3.4])

The first three numbers encode rotation as a rotation vector:


In [ ]:
tf_rot = Tf.from_exp_coords([0.5, 0.3, 0.1, 0, 0, 0])
tf_rot.rotation.as_rotvec()

array([0.5, 0.3, 0.1])

Combining translation and rotation preserves the rotation vector,
but changes the last three components as they encode translation and
rotation:


In [ ]:
(tf_trans * tf_rot).as_exp_coords()

array([0.5, 0.3, 0.1, 3.64305882, -1.25879559, 4.46109265])