<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy import linalg
a = np.array([[1., 2.], [3., 4.]])
linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
a @ linalg.inv(a)

array([[ 1.,  0.],
       [ 0.,  1.]])

The input array ``a`` may represent a single matrix or a collection (a.k.a.
a "batch") of square matrices. For example, if ``a.shape == (4, 3, 2, 2)``, it is
interpreted as a ``(4, 3)``-shaped batch of $2\times 2$ matrices.
See :ref:`linalg_batch` for further details.
To illustrate:


In [ ]:
a = np.stack((np.eye(2), [[1, 2], [3, 4]]))
linalg.inv(a)

array([[[ 1. ,  0. ],
        [ 0. ,  1. ]],
       [[-2. ,  1. ],
        [ 1.5, -0.5]]])

Note that the structure detection runs per-slice: in the example above, each of the
two slices will be independently discovered as being diagonal. Setting an explicit
``assume_a`` argument will bypass structure detection and use the provided value
without checking:


In [ ]:
a = np.stack((np.eye(2), [[1, 2], [3, 4]]))
linalg.inv(a, assume_a="diagonal")

array([[[1.  , 0.  ],
        [0.  , 1.  ]],
       [[1.  , 2.  ],   # off-diagonal elements are incorrect
        [3.  , 0.25]]])