<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In the following example `iv` returns infinity whereas `ive` still returns
a finite number.


In [ ]:
from scipy.special import iv, ive
import numpy as np
import matplotlib.pyplot as plt
iv(3, 1000.), ive(3, 1000.)

(inf, 0.01256056218254712)

Evaluate the function at one point for different orders by
providing a list or NumPy array as argument for the `v` parameter:


In [ ]:
ive([0, 1, 1.5], 1.)

array([0.46575961, 0.20791042, 0.10798193])

Evaluate the function at several points for order 0 by providing an
array for `z`.


In [ ]:
points = np.array([-2., 0., 3.])
ive(0, points)

array([0.30850832, 1.        , 0.24300035])

Evaluate the function at several points for different orders by
providing arrays for both `v` for `z`. Both arrays have to be
broadcastable to the correct shape. To calculate the orders 0, 1
and 2 for a 1D array of points:


In [ ]:
ive([[0], [1], [2]], points)

array([[ 0.30850832,  1.        ,  0.24300035],
       [-0.21526929,  0.        ,  0.19682671],
       [ 0.09323903,  0.        ,  0.11178255]])

Plot the functions of order 0 to 3 from -5 to 5.


In [ ]:
fig, ax = plt.subplots()
x = np.linspace(-5., 5., 1000)
for i in range(4):
    ax.plot(x, ive(i, x), label=fr'$I_{i!r}(z)\cdot e^{{-|z|}}$')
ax.legend()
ax.set_xlabel(r"$z$")
plt.show()