<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Compare the output of `yv` and `yve` for large complex arguments for `z`
by computing their values for order ``v=1`` at ``z=1000j``. We see that
`yv` returns nan but `yve` returns a finite number:


In [ ]:
import numpy as np
from scipy.special import yv, yve
v = 1
z = 1000j
yv(v, z), yve(v, z)

((nan+nanj), (-0.012610930256928629+7.721967686709076e-19j))

For real arguments for `z`, `yve` returns the same as `yv` up to
floating point errors.


In [ ]:
v, z = 1, 1000
yv(v, z), yve(v, z)

(-0.02478433129235178, -0.02478433129235179)

The function can be evaluated for several orders at the same time by
providing a list or NumPy array for `v`:


In [ ]:
yve([1, 2, 3], 1j)

array([-0.20791042+0.14096627j,  0.38053618-0.04993878j,
       0.00815531-1.66311097j])

In the same way, the function can be evaluated at several points in one
call by providing a list or NumPy array for `z`:


In [ ]:
yve(1, np.array([1j, 2j, 3j]))

array([-0.20791042+0.14096627j, -0.21526929+0.01205044j,
       -0.19682671+0.00127278j])

It is also possible to evaluate several orders at several points
at the same time by providing arrays for `v` and `z` with
broadcasting compatible shapes. Compute `yve` for two different orders
`v` and three points `z` resulting in a 2x3 array.


In [ ]:
v = np.array([[1], [2]])
z = np.array([3j, 4j, 5j])
v.shape, z.shape

((2, 1), (3,))

In [ ]:
yve(v, z)

array([[-1.96826713e-01+1.27277544e-03j, -1.78750840e-01+1.45558819e-04j,
        -1.63972267e-01+1.73494110e-05j],
       [1.94960056e-03-1.11782545e-01j,  2.02902325e-04-1.17626501e-01j,
        2.27727687e-05-1.17951906e-01j]])