<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import lsmr
A = csc_matrix([[1., 0.], [1., 1.], [0., 1.]], dtype=float)

The first example has the trivial solution ``[0, 0]``


In [ ]:
b = np.array([0., 0., 0.], dtype=float)
x, istop, itn, normr = lsmr(A, b)[:4]
istop

0

In [ ]:
x

array([0., 0.])

The stopping code ``istop=0`` returned indicates that a vector of zeros was
found as a solution. The returned solution `x` indeed contains
``[0., 0.]``. The next example has a non-trivial solution:


In [ ]:
b = np.array([1., 0., -1.], dtype=float)
x, istop, itn, normr = lsmr(A, b)[:4]
istop

1

In [ ]:
x

array([ 1., -1.])

In [ ]:
itn

1

In [ ]:
normr

4.440892098500627e-16

As indicated by ``istop=1``, `lsmr` found a solution obeying the tolerance
limits. The given solution ``[1., -1.]`` obviously solves the equation. The
remaining return values include information about the number of iterations
(`itn=1`) and the remaining difference of left and right side of the solved
equation.
The final example demonstrates the behavior in the case where there is no
solution for the equation:


In [ ]:
b = np.array([1., 0.01, -1.], dtype=float)
x, istop, itn, normr = lsmr(A, b)[:4]
istop

2

In [ ]:
x

array([ 1.00333333, -0.99666667])

In [ ]:
A.dot(x)-b

array([ 0.00333333, -0.00333333,  0.00333333])

In [ ]:
normr

0.005773502691896255

`istop` indicates that the system is inconsistent and thus `x` is rather an
approximate solution to the corresponding least-squares problem. `normr`
contains the minimal distance that was found.