<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.special import roots_sh_chebyt
roots, weights = roots_sh_chebyt(5)
roots

array([0.02447174, 0.20610737, 0.5       , 0.79389263, 0.97552826])

In [ ]:
weights

array([0.62831853, 0.62831853, 0.62831853, 0.62831853, 0.62831853])

Verify that the values in `roots` are roots of the shifted Chebyshev
polynomial of the first kind $T^*_5(x)=T_5(2x-1)$.


In [ ]:
from scipy.special import eval_chebyt, eval_sh_chebyt
eval_chebyt(5, 2*roots-1)

array([8.8817842e-16, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       8.8817842e-16])

In [ ]:
eval_sh_chebyt(5, roots)

array([8.8817842e-16, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       8.8817842e-16])

The values of $T_5(2x-1)$ and of $T^*_5(x)$ evaluated at the
roots are indeed zero or very close to it.

Verify that the sum of the weights equals the integral from 0 to 1 of
$1/\sqrt{x-x^2}$ which evaluates to $\pi$. There are two ways
to obtain the sum of weights, both resulting in $\pi$ within numerical
precision.


In [ ]:
sum(weights)

np.float64(3.141592653589793)

In [ ]:
roots, weights, sum_of_weights = roots_sh_chebyt(5, mu=True)
sum_of_weights

3.141592653589793

Roots and weights obtained from the shifted Chebyshev polynomial of the
first kind $T^*_n(x)$ are used in Gauss-Chebyshev quadrature where
the integral from 0 to 1 of $f(x)/\sqrt{x-x^2}$ is evaluated.
Roots and weights for order $n$ are expected to yield the exact
result for polynomials $f(x)$ of a maximal order of $2n-1$.


In [ ]:
f = lambda x: x**4
weights @ f(roots)

np.float64(0.8590292412159591)

The exact result is $35\pi/128$.


In [ ]:
from math import cos, pi
35*pi/128

0.859029241215959

In general, Gauss-Chebyshev quadrature will only yield an approximate value of the
integral. Consider the integral from 0 to 1 of $\cos(x)/\sqrt{x-x^2}$
which evaluates to $\pi\cos(1/2) J_0(1/2)$, where $J_0$ is the Bessel
function of first kind and order 0.


In [ ]:
import numpy as np
weights @ np.cos(roots)

np.float64(2.5873677615532227)

In [ ]:
from scipy.special import jv
pi * cos(0.5) * jv(0, 0.5)

np.float64(2.587367761551782)