<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Calculate the Struve function of order 1 at 2.


In [ ]:
import numpy as np
from scipy.special import struve
import matplotlib.pyplot as plt
struve(1, 2.)

0.6467637282835622

Calculate the Struve function at 2 for orders 1, 2 and 3 by providing
a list for the order parameter `v`.


In [ ]:
struve([1, 2, 3], 2.)

array([0.64676373, 0.28031806, 0.08363767])

Calculate the Struve function of order 1 for several points by providing
an array for `x`.


In [ ]:
points = np.array([2., 5., 8.])
struve(1, points)

array([0.64676373, 0.80781195, 0.48811605])

Compute the Struve function for several orders at several points by
providing arrays for `v` and `z`. The arrays have to be broadcastable
to the correct shapes.


In [ ]:
orders = np.array([[1], [2], [3]])
points.shape, orders.shape

((3,), (3, 1))

In [ ]:
struve(orders, points)

array([[0.64676373, 0.80781195, 0.48811605],
       [0.28031806, 1.56937455, 1.51769363],
       [0.08363767, 1.50872065, 2.98697513]])

Plot the Struve functions of order 0 to 3 from -10 to 10.


In [ ]:
fig, ax = plt.subplots()
x = np.linspace(-10., 10., 1000)
for i in range(4):
    ax.plot(x, struve(i, x), label=f'$H_{i!r}$')
ax.legend(ncol=2)
ax.set_xlim(-10, 10)
ax.set_title(r"Struve functions $H_{\nu}$")
plt.show()