<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy import ndimage
a = np.zeros((6, 6), dtype=int)
a[2:4, 2:4] = 1
a[4, 4] = 1
a[:2, :3] = 2
a[0, 5] = 3
a

array([[2, 2, 2, 0, 0, 3],
       [2, 2, 2, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
val_indices = ndimage.value_indices(a)

The dictionary `val_indices` will have an entry for each distinct
value in the input array.


In [ ]:
val_indices.keys()

dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3)])

The entry for each value is an index tuple, locating the elements
with that value.


In [ ]:
ndx1 = val_indices[1]
ndx1

(array([2, 2, 3, 3, 4]), array([2, 3, 2, 3, 4]))

This can be used to index into the original array, or any other
array with the same shape.


In [ ]:
a[ndx1]

array([1, 1, 1, 1, 1])

If the zeros were to be ignored, then the resulting dictionary
would no longer have an entry for zero.


In [ ]:
val_indices = ndimage.value_indices(a, ignore_value=0)
val_indices.keys()

dict_keys([np.int64(1), np.int64(2), np.int64(3)])