<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Apply a 1-D median filter to an array containing noise spikes.


In [ ]:
import numpy as np
from scipy import signal
x = np.array([1, 2, 100, 2, 1, 1, 35, 30, 1])

Apply a filter with a kernel size of 3:


In [ ]:
signal.medfilt(x, kernel_size=3)

array([ 1,  2,  2,  2,  1,  1, 30, 30,  1])

The size 3 kernel is not big enough to eliminate the
2-wide spike near the end of the array.
A larger size 5 kernel successfully eliminates the 2-wide spike.


In [ ]:
signal.medfilt(x, kernel_size=5)

array([1, 2, 2, 2, 2, 2, 1, 1, 1])

Kernel size 1 acts as an identity operator.


In [ ]:
signal.medfilt(x, kernel_size=1)

array([  1,   2, 100,   2,   1,   1,  35,  30,   1])