<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

An Hadamard matrix, which has orthogonal columns, so we expect that
the suspace angle to be $\frac{\pi}{2}$:


In [ ]:
import numpy as np
from scipy.linalg import hadamard, subspace_angles
rng = np.random.default_rng()
H = hadamard(4)
print(H)

[[ 1  1  1  1]
 [ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]

In [ ]:
np.rad2deg(subspace_angles(H[:, :2], H[:, 2:]))

array([ 90.,  90.])

And the subspace angle of a matrix to itself should be zero:


In [ ]:
subspace_angles(H[:, :2], H[:, :2]) <= 2 * np.finfo(float).eps

array([ True,  True], dtype=bool)

The angles between non-orthogonal subspaces are in between these extremes:


In [ ]:
x = rng.standard_normal((4, 3))
np.rad2deg(subspace_angles(x[:, :2], x[:, [2]]))

array([ 55.832])  # random