<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
import scipy.special as sc

Its domain is nonnegative n and x.


In [ ]:
sc.expn(-1, 1.0), sc.expn(1, -1.0)

(nan, nan)

It has a pole at ``x = 0`` for ``n = 1, 2``; for larger ``n`` it
is equal to ``1 / (n - 1)``.


In [ ]:
sc.expn([0, 1, 2, 3, 4], 0)

array([       inf,        inf, 1.        , 0.5       , 0.33333333])

For n equal to 0 it reduces to ``exp(-x) / x``.


In [ ]:
x = np.array([1, 2, 3, 4])
sc.expn(0, x)

array([0.36787944, 0.06766764, 0.01659569, 0.00457891])

In [ ]:
np.exp(-x) / x

array([0.36787944, 0.06766764, 0.01659569, 0.00457891])

For n equal to 1 it reduces to `exp1`.


In [ ]:
sc.expn(1, x)

array([0.21938393, 0.04890051, 0.01304838, 0.00377935])

In [ ]:
sc.exp1(x)

array([0.21938393, 0.04890051, 0.01304838, 0.00377935])