<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import expm, expm_multiply
A = csc_matrix([[1, 0], [0, 1]])
A.toarray()

array([[1, 0],
       [0, 1]], dtype=int64)

In [ ]:
B = np.array([np.exp(-1.), np.exp(-2.)])
B

array([ 0.36787944,  0.13533528])

In [ ]:
expm_multiply(A, B, start=1, stop=2, num=3, endpoint=True)

array([[ 1.        ,  0.36787944],
       [ 1.64872127,  0.60653066],
       [ 2.71828183,  1.        ]])

In [ ]:
expm(A).dot(B)                  # Verify 1st timestep

array([ 1.        ,  0.36787944])

In [ ]:
expm(1.5*A).dot(B)              # Verify 2nd timestep

array([ 1.64872127,  0.60653066])

In [ ]:
expm(2*A).dot(B)                # Verify 3rd timestep

array([ 2.71828183,  1.        ])