<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Import all necessary modules.


In [ ]:
import numpy as np
from scipy.special import pseudo_huber, huber
import matplotlib.pyplot as plt

Calculate the function for ``delta=1`` at ``r=2``.


In [ ]:
pseudo_huber(1., 2.)

1.2360679774997898

Calculate the function at ``r=2`` for different `delta` by providing
a list or NumPy array for `delta`.


In [ ]:
pseudo_huber([1., 2., 4.], 3.)

array([2.16227766, 3.21110255, 4.        ])

Calculate the function for ``delta=1`` at several points by providing
a list or NumPy array for `r`.


In [ ]:
pseudo_huber(2., np.array([1., 1.5, 3., 4.]))

array([0.47213595, 1.        , 3.21110255, 4.94427191])

The function can be calculated for different `delta` and `r` by
providing arrays for both with compatible shapes for broadcasting.


In [ ]:
r = np.array([1., 2.5, 8., 10.])
deltas = np.array([[1.], [5.], [9.]])
print(r.shape, deltas.shape)

(4,) (3, 1)

In [ ]:
pseudo_huber(deltas, r)

array([[ 0.41421356,  1.6925824 ,  7.06225775,  9.04987562],
       [ 0.49509757,  2.95084972, 22.16990566, 30.90169944],
       [ 0.49846624,  3.06693762, 27.37435121, 40.08261642]])

Plot the function for different `delta`.


In [ ]:
x = np.linspace(-4, 4, 500)
deltas = [1, 2, 3]
linestyles = ["dashed", "dotted", "dashdot"]
fig, ax = plt.subplots()
combined_plot_parameters = list(zip(deltas, linestyles))
for delta, style in combined_plot_parameters:
    ax.plot(x, pseudo_huber(delta, x), label=rf"$\delta={delta}$",
            ls=style)
ax.legend(loc="upper center")
ax.set_xlabel("$x$")
ax.set_title(r"Pseudo-Huber loss function $h_{\delta}(x)$")
ax.set_xlim(-4, 4)
ax.set_ylim(0, 8)
plt.show()

Finally, illustrate the difference between `huber` and `pseudo_huber` by
plotting them and their gradients with respect to `r`. The plot shows
that `pseudo_huber` is continuously differentiable while `huber` is not
at the points $\pm\delta$.


In [ ]:
def huber_grad(delta, x):
    grad = np.copy(x)
    linear_area = np.argwhere(np.abs(x) > delta)
    grad[linear_area]=delta*np.sign(x[linear_area])
    return grad
def pseudo_huber_grad(delta, x):
    return x* (1+(x/delta)**2)**(-0.5)
x=np.linspace(-3, 3, 500)
delta = 1.
fig, ax = plt.subplots(figsize=(7, 7))
ax.plot(x, huber(delta, x), label="Huber", ls="dashed")
ax.plot(x, huber_grad(delta, x), label="Huber Gradient", ls="dashdot")
ax.plot(x, pseudo_huber(delta, x), label="Pseudo-Huber", ls="dotted")
ax.plot(x, pseudo_huber_grad(delta, x), label="Pseudo-Huber Gradient",
        ls="solid")
ax.legend(loc="upper center")
plt.show()