<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
import scipy.special as sc

As z goes to infinity along the real axis, S and C converge to 0.5.


In [ ]:
S, C = sc.fresnel([0.1, 1, 10, 100, np.inf])
S

array([0.00052359, 0.43825915, 0.46816998, 0.4968169 , 0.5       ])

In [ ]:
C

array([0.09999753, 0.7798934 , 0.49989869, 0.4999999 , 0.5       ])

They are related to the error function `erf`.


In [ ]:
z = np.array([1, 2, 3, 4])
zeta = 0.5 * np.sqrt(np.pi) * (1 - 1j) * z
S, C = sc.fresnel(z)
C + 1j*S

array([0.7798934 +0.43825915j, 0.48825341+0.34341568j,
       0.60572079+0.496313j  , 0.49842603+0.42051575j])

In [ ]:
0.5 * (1 + 1j) * sc.erf(zeta)

array([0.7798934 +0.43825915j, 0.48825341+0.34341568j,
       0.60572079+0.496313j  , 0.49842603+0.42051575j])