<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy import linalg
a = np.array([[  3.,  -2.,  -2.],
              [  6.,  -7.,   4.],
              [  7.,   8.,  -6.]])
q, r = linalg.qr(a)

Given this QR decomposition, update q and r when 2 rows are inserted.


In [ ]:
u = np.array([[  6.,  -9.,  -3.],
              [ -3.,  10.,   1.]])
q1, r1 = linalg.qr_insert(q, r, u, 2, 'row')
q1

array([[-0.25445668,  0.02246245,  0.18146236, -0.72798806,  0.60979671],  # may vary (signs)
       [-0.50891336,  0.23226178, -0.82836478, -0.02837033, -0.00828114],
       [-0.50891336,  0.35715302,  0.38937158,  0.58110733,  0.35235345],
       [ 0.25445668, -0.52202743, -0.32165498,  0.36263239,  0.65404509],
       [-0.59373225, -0.73856549,  0.16065817, -0.0063658 , -0.27595554]])

In [ ]:
r1

array([[-11.78982612,   6.44623587,   3.81685018],  # may vary (signs)
       [  0.        , -16.01393278,   3.72202865],
       [  0.        ,   0.        ,  -6.13010256],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ]])

The update is equivalent, but faster than the following.


In [ ]:
a1 = np.insert(a, 2, u, 0)
a1

array([[  3.,  -2.,  -2.],
       [  6.,  -7.,   4.],
       [  6.,  -9.,  -3.],
       [ -3.,  10.,   1.],
       [  7.,   8.,  -6.]])

In [ ]:
q_direct, r_direct = linalg.qr(a1)

Check that we have equivalent results:


In [ ]:
np.dot(q1, r1)

array([[  3.,  -2.,  -2.],
       [  6.,  -7.,   4.],
       [  6.,  -9.,  -3.],
       [ -3.,  10.,   1.],
       [  7.,   8.,  -6.]])

In [ ]:
np.allclose(np.dot(q1, r1), a1)

True

And the updated Q is still unitary:


In [ ]:
np.allclose(np.dot(q1.T, q1), np.eye(5))

True