<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

The following example builds b(z) / a(z) back from its
partial-fraction expansion:


In [ ]:
import numpy as np
from scipy import signal
r = np.array([-2.2, 3.2])
p = np.array([0.25, 0.5])
k = np.array([])
b, a = signal.invresz(r, p, k)
b

array([1. , 0.3])

In [ ]:
a

array([ 1.   , -0.75 ,  0.125])

Use `residuez` to get back the expansion:


In [ ]:
signal.residuez(b, a)

(array([-2.2,  3.2]), array([0.25, 0.5 ]), array([], dtype=float64))

A non-empty `k` adds the direct term:


In [ ]:
r = np.array([0.4])
p = np.array([0.5])
k = np.array([1.6, -0.2])
b, a = signal.invresz(r, p, k)
b, a

(array([ 2. , -1. ,  0.1]), array([ 1. , -0.5]))