<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Solve the Toeplitz system T x = b, where
```

[ 1 -1 -2 -3]       [1]
T = [ 3  1 -1 -2]   b = [2]
[ 6  3  1 -1]       [2]
[10  6  3  1]       [5]

```
To specify the Toeplitz matrix, only the first column and the first
row are needed.


In [ ]:
import numpy as np
c = np.array([1, 3, 6, 10])    # First column of T
r = np.array([1, -1, -2, -3])  # First row of T
b = np.array([1, 2, 2, 5])

In [ ]:
from scipy.linalg import solve_toeplitz, toeplitz
x = solve_toeplitz((c, r), b)
x

array([ 1.66666667, -1.        , -2.66666667,  2.33333333])

Check the result by creating the full Toeplitz matrix and
multiplying it by `x`.  We should get `b`.


In [ ]:
T = toeplitz(c, r)
T.dot(x)

array([ 1.,  2.,  2.,  5.])