<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import RigidTransform as Tf
from scipy.spatial.transform import Rotation as R
import numpy as np

Recover the rotation and translation from a transform:


In [ ]:
t = np.array([2, 3, 4])
r = R.from_matrix([[0, 0, 1],
                   [1, 0, 0],
                   [0, 1, 0]])
tf = Tf.from_components(t, r)
t, r = tf.as_components()
t

array([2., 3., 4.])

In [ ]:
r.as_matrix()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

The transform applied to a vector is equivalent to the rotation applied
to the vector, followed by the translation:


In [ ]:
t + r.apply([1, 0, 0])

array([2., 4., 4.])

In [ ]:
tf.apply([1, 0, 0])

array([2., 4., 4.])